export const UPDATE_ACTION_TYPE = 'NEW_ACTION_MODAL/UPDATE_ACTION_TYPE';
export const UPDATE_ACTION_TEXT = 'NEW_ACTION_MODAL/UPDATE_ACTION_TEXT';
export const UPDATE_ACTION_TIME = 'NEW_ACTION_MODAL/UPDATE_ACTION_TIME';
export const ERROR = 'NEW_ACTION_MODAL/ERROR';
export const INIT = 'NEW_ACTION_MODAL/INIT';
